// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matrix.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_matrix_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_matrix_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_matrix_2eproto;
class protoMatrix;
struct protoMatrixDefaultTypeInternal;
extern protoMatrixDefaultTypeInternal _protoMatrix_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::protoMatrix* Arena::CreateMaybeMessage<::protoMatrix>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class protoMatrix final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:protoMatrix) */ {
 public:
  inline protoMatrix() : protoMatrix(nullptr) {}
  ~protoMatrix() override;
  explicit PROTOBUF_CONSTEXPR protoMatrix(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  protoMatrix(const protoMatrix& from);
  protoMatrix(protoMatrix&& from) noexcept
    : protoMatrix() {
    *this = ::std::move(from);
  }

  inline protoMatrix& operator=(const protoMatrix& from) {
    CopyFrom(from);
    return *this;
  }
  inline protoMatrix& operator=(protoMatrix&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const protoMatrix& default_instance() {
    return *internal_default_instance();
  }
  static inline const protoMatrix* internal_default_instance() {
    return reinterpret_cast<const protoMatrix*>(
               &_protoMatrix_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(protoMatrix& a, protoMatrix& b) {
    a.Swap(&b);
  }
  inline void Swap(protoMatrix* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(protoMatrix* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  protoMatrix* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<protoMatrix>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const protoMatrix& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const protoMatrix& from) {
    protoMatrix::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(protoMatrix* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "protoMatrix";
  }
  protected:
  explicit protoMatrix(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kHeightFieldNumber = 1,
    kWidthFieldNumber = 2,
  };
  // repeated double data = 3;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  double _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      _internal_data() const;
  void _internal_add_data(double value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      _internal_mutable_data();
  public:
  double data(int index) const;
  void set_data(int index, double value);
  void add_data(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
      mutable_data();

  // int32 height = 1;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // int32 width = 2;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:protoMatrix)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< double > data_;
    int32_t height_;
    int32_t width_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matrix_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// protoMatrix

// int32 height = 1;
inline void protoMatrix::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t protoMatrix::_internal_height() const {
  return _impl_.height_;
}
inline int32_t protoMatrix::height() const {
  // @@protoc_insertion_point(field_get:protoMatrix.height)
  return _internal_height();
}
inline void protoMatrix::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void protoMatrix::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:protoMatrix.height)
}

// int32 width = 2;
inline void protoMatrix::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t protoMatrix::_internal_width() const {
  return _impl_.width_;
}
inline int32_t protoMatrix::width() const {
  // @@protoc_insertion_point(field_get:protoMatrix.width)
  return _internal_width();
}
inline void protoMatrix::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void protoMatrix::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:protoMatrix.width)
}

// repeated double data = 3;
inline int protoMatrix::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int protoMatrix::data_size() const {
  return _internal_data_size();
}
inline void protoMatrix::clear_data() {
  _impl_.data_.Clear();
}
inline double protoMatrix::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline double protoMatrix::data(int index) const {
  // @@protoc_insertion_point(field_get:protoMatrix.data)
  return _internal_data(index);
}
inline void protoMatrix::set_data(int index, double value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:protoMatrix.data)
}
inline void protoMatrix::_internal_add_data(double value) {
  _impl_.data_.Add(value);
}
inline void protoMatrix::add_data(double value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:protoMatrix.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
protoMatrix::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >&
protoMatrix::data() const {
  // @@protoc_insertion_point(field_list:protoMatrix.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
protoMatrix::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< double >*
protoMatrix::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:protoMatrix.data)
  return _internal_mutable_data();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_matrix_2eproto
